version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=stationSki
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  app-doukali:
    depends_on:
      - mysqldb
    image: doukali/doukali-backend:latest
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path" : "/api",
        "server.port" : "8089",
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true


  frontend:
    depends_on:
      - app-doukali
    image: doukali/doukali-frontend:latest
    ports:
      - "4200:80"

volumes:
  db: